### PR TITLE
Depend on hamcrest-core instead of library.

### PR DESCRIPTION
**Pull request by stefanbirkner**
Avoid dependencies on libraries that are not used.

### CODE REVIEW

**Comment by jahed** [comment]
Does Hamcrest fall under the `test` scope? It's used to actually provide the library, not just to test it.

**Comment by CliveEvans** [comment]
It's not so much to provide it, but it is a compile time dependency of the library, so yes, scope of hamcrest-core is `compile` (default) not `test`.

hamcrest-library is used in `test` scope only.

**Comment by CliveEvans** [comment]
Can you push the button @jahed? I no longer have the keys ...

**Comment by jahed** [comment]
My bad, completely misread the diff on my phone.

I'll get it released tomorrow.

**Comment by CliveEvans** [comment]
I made the same mistake when I first looked at it.

Thanks mate.

**Comment by CliveEvans** [comment]
Thanks @stefanbirkner

**Comment by jahed** [comment]
Released in v1.4

**Pull request merged**
